name: Cleanup
on:
  workflow_dispatch:
jobs:
  delete:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Remove .github directory
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "GitHub Actions"
          git rm -r .github/
          git commit -m "Remove .github directory"
          git push
